export const RANKING_SLOT_POINTS = 100;
export const RANKING_ALBUM_PCT_MULTIPLIER = 5;
export const RANKING_MISSION_BONUS = 40;
export const RANKING_TRADE_BONUS = 25;
export const RANKING_EFFICIENCY_MULTIPLIER = 30;
export const RANKING_PACK_PENALTY = 3;
export const RANKING_ZERO_PASTE_EFFICIENCY_BONUS = 2;
